import React, { useEffect, useState } from 'react';
import ScrollPageContent from './ScrollPageContent';
import { Button, LinearProgress } from '@material-ui/core';
import { makeStyles } from '@material-ui/core/styles';
import { useLocation } from 'react-router-dom';

export interface IScrollPageProps {
    /**
     * Children to display, each will be wrapped with ScrollPageContent
     */
    children: React.ReactNode;
    /**
     * Make active page controllable
     */
    activePage?: number;
    /**
     * Show progress bar
     */
    progressBar: boolean;
    /**
     * Show next button
     */
    showNextButton: boolean;
    /**
     * Position for progress bar
     */
    progressBarLocation?: 'top' | 'bottom';
    /**
     * Class with styles (generated by useStyles)
     */
    pageClassName?: string
}


const useStyles = makeStyles({
    progressWrapper: {
        position: 'fixed',
        width: '100%'
    },
    top: {
        top: 0
    },
    bottom: {
        bottom: 0
    }
})


const scrollToPercents = (scrollSize: number, scrollDistance: number, innerHeight: number, topOffset: number): number => {
    scrollSize -= innerHeight;
    scrollDistance -= topOffset;
    scrollDistance = scrollDistance < 0 ? 0 : scrollDistance;

    return Math.round((1 - (scrollSize - scrollDistance) / scrollSize) * 100);
}


function useQuery () {
    return new URLSearchParams(useLocation().search);
}


const ScrollPage = (props: IScrollPageProps) => {
    const {
        children,
        activePage,
        progressBar,
        progressBarLocation,
        showNextButton,
        pageClassName,
    } = props;

    const params = useQuery();
    const pageGetParameter = params.has('page') ? parseInt(params.get('page') as string) : undefined;

    const [innerHeight, setInnerHeight] = useState(window.innerHeight);
    const [scrollSize, setScrollSize] = useState(window.innerHeight);
    const [distanceFromTop, setDistanceFromTop] = useState(0);
    const [scrolledPercents, setScrolledPercents] = useState(0);
    const [activePageInternal, setActivePage] = useState(pageGetParameter || 0);
    const classes = useStyles();


    // mount-unmount handlers
    // window resizing and scrolling events
    useEffect(() => {
        const scrollHandler = (): void => {
            setScrolledPercents(scrollToPercents(scrollSize, window.pageYOffset, innerHeight, distanceFromTop));
        }

        const resizeHandler = (): void => {
            setInnerHeight(window.innerHeight);
        }

        window.addEventListener('resize', resizeHandler);
        window.addEventListener('scroll', scrollHandler);

        return () => {
            window.removeEventListener('resize', resizeHandler);
            window.removeEventListener('scroll', scrollHandler);
        }
    }, [scrollSize, innerHeight, distanceFromTop]);


    // ScrollPage size
    const scrollPageRef = (element: HTMLDivElement) => {
        if (element) {
            setScrollSize(element.scrollHeight);
            setDistanceFromTop(element.offsetTop);
        }
    };

    const setNewPage = (pageNumber: number) => {
        setActivePage(pageNumber);
    }


    // wrap children with pages
    const pageChildren = React.Children.map(children, (child, i) => {
        const active = pageGetParameter || activePage || activePageInternal;

        return <ScrollPageContent
            pageHeight={innerHeight}
            isActive={i === active}
            className={pageClassName}
        >
            {child}
            {
                showNextButton ?
                    <div>
                        <Button
                            onClick={() => setNewPage(i + 1)}
                        >
                            Next
                        </Button>
                    </div>
                    : null
            }
        </ScrollPageContent>
    });


    return (
        <div
            ref={scrollPageRef}
        >
            {
                progressBar ?
                    <div
                        className={`${
                            classes.progressWrapper
                        } ${
                            progressBarLocation === 'top' ? classes.top : classes.bottom
                        }`}
                    >
                        <LinearProgress
                            variant='determinate'
                            value={scrolledPercents}
                        />
                    </div> :
                    null
            }
            {pageChildren}
        </div>
    );
};

export default ScrollPage;
